# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the \"License\"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an \"AS IS\" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Flow Controller:
  name: MiNiFi MOJO Py Real Time Scoring Flow
Processors:
    - name: GetFile
      class: GetFile
      scheduling strategy: TIMER_DRIVEN
      scheduling period: 120 sec
      Properties:
        Keep Source File: true
        Input Directory: /home/ubuntu/daimojo-minificpp/testData/test-real-time-data/

    - name: ExecuteDaiMojoScoringPipeline
      class: ExecuteDaiMojoScoringPipeline
      Properties:
        Script File: /home/ubuntu/nifi-minifi-cpp-0.7.0/minifi-python/h2o/dai/msp/ExecuteDaiMojoScoringPipeline.py
        MOJO Pipeline Filepath: /home/ubuntu/daimojo-minificpp/mojo-pipeline/pipeline.mojo

    - name: ConvertDsToCsv
      class: ConvertDsToCsv
      Properties:
        Script File: /home/ubuntu/nifi-minifi-cpp-0.7.0/minifi-python/h2o/ConvertDsToCsv.py
      
    - name: LogAttribute
      class: LogAttribute
      Properties:
        Log Level: info

    - name: UpdateAttribute
      class: UpdateAttribute
      Properties:
        filename: hydraulic-real-time-scores-${UUID()}.csv

    - name: PutFile
      class: PutFile
      Properties:
        Directory: /home/ubuntu/daimojo-minificpp/predData/pred-real-time-data/
        Conflict Resolution Strategy: replace

Connections:
    - source name: GetFile
      source relationship name: success
      destination name: ExecuteDaiMojoScoringPipeline

    - source name: ExecuteDaiMojoScoringPipeline
      source relationship name: success
      destination name: ConvertDsToCsv

    - source name: ConvertDsToCsv
      source relationship name: success
      destination name: LogAttribute

    - source name: ConvertDsToCsv
      source relationship name: success
      destination name: UpdateAttribute

    - source name: UpdateAttribute
      source relationship name: success
      destination name: PutFile

Remote Processing Groups: []
Provenance Reporting:
